spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password: qwer
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create  # ?????? ?? ??? ???? drop?? ?? ????.
    properties:
      hibernate:
        #      show_sql: true   # System.out? ?????? ?? SQL? ???.
        format_sql: true
logging.level:
  org.hibernate.SQL: debug  # logger? ?? ?????? ?? SQL? ???.
  org.hibernate.type: trace # Sql ?? ????? ??? ??? (?? ?? ?? ??)

server:
  port: 8888